### ISSUE TITLE
false argument gives ERROR: invalid input syntax for type boolean: ""

### ISSUE THREAD

**Issue by ledazinha** [voryx/PgAsync#10]
The statement fails when trying to set a boolean column to php `false`. It does work, however, with integer value zero or the string `'false'`:

```php
require 'vendor/autoload.php';

$client = new \PgAsync\Client([
    'host' => '127.0.0.1',
    'port' => 5432,
    'user' => 'username',
    'password' => 'password',
    'database' => 'database',
], \EventLoop\getLoop());

//$args = [true, 1];   // ok
//$args = ['true', 1]; // ok
//$args = ['t', 1]; // ok
//$args = [1, 1]; // ok
$args = [false, 1]; // this fails
//$args['false', 1]; // ok
//$args = ['f', 1]; // ok
//$args = [0, 1]; // ok

$upd = 'UPDATE test SET b = $1 WHERE id = $2 RETURNING *';
$client->executeStatement($upd, $args)->subscribe(
    new \Rx\Observer\CallbackObserver(
        function ($row) {
            echo "Result.\n";
            var_dump($row);
        },
        function ($e) {
            echo "Failed.\n";
            echo $e, PHP_EOL;
            \EventLoop\getLoop()->stop();
        },
        function () {
            echo "Complete.\n";
            \EventLoop\getLoop()->stop();
        }
    )
);
```

Dataset:
```sql
CREATE TABLE test (
    id serial not null,
    b boolean,
    primary key(id)
);
insert into test(b) values(true);
```

Result:
```
Failed.
exception 'PgAsync\ErrorException' with message 'ERROR: invalid input syntax for type boolean: "" while executing "UPDATE test SET b = $1 WHERE id = $2 RETURNING *"' in /vagrant/project/vendor/voryx/pgasync/src/PgAsync/Connection.php:386
Stack trace:
#0 /vagrant/project/vendor/voryx/pgasync/src/PgAsync/Connection.php(260): PgAsync\Connection->handleErrorResponse(Object(PgAsync\Message\ErrorResponse))
#1 /vagrant/project/vendor/voryx/pgasync/src/PgAsync/Connection.php(211): PgAsync\Connection->handleMessage(Object(PgAsync\Message\ErrorResponse))
#2 /vagrant/project/vendor/voryx/pgasync/src/PgAsync/Connection.php(231): PgAsync\Connection->onData('E\x00\x00\x00SSERROR\x00C22...')
#3 /vagrant/project/vendor/voryx/pgasync/src/PgAsync/Connection.php(216): PgAsync\Connection->onData('E\x00\x00\x00SSERROR\x00C22...')
#4 /vagrant/project/vendor/voryx/pgasync/src/PgAsync/Connection.php(231): PgAsync\Connection->onData('1\x00\x00\x00\x04E\x00\x00\x00SSERRO...')
#5 /vagrant/project/vendor/voryx/pgasync/src/PgAsync/Connection.php(216): PgAsync\Connection->onData('1\x00\x00\x00\x04E\x00\x00\x00SSERRO...')
#6 /vagrant/project/vendor/voryx/pgasync/src/PgAsync/Connection.php(231): PgAsync\Connection->onData('3\x00\x00\x00\x041\x00\x00\x00\x04E\x00\x00\x00S...')
#7 [internal function]: PgAsync\Connection->onData('3\x00\x00\x00\x041\x00\x00\x00\x04E\x00\x00\x00S...', Object(React\Stream\Stream))
#8 /vagrant/project/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Array, Array)
#9 /vagrant/project/vendor/react/stream/src/Stream.php(133): Evenement\EventEmitter->emit('data', Array)
#10 [internal function]: React\Stream\Stream->handleData(Resource id #55, Object(React\EventLoop\StreamSelectLoop))
#11 /vagrant/project/vendor/react/event-loop/src/StreamSelectLoop.php(232): call_user_func(Array, Resource id #55, Object(React\EventLoop\StreamSelectLoop))
#12 /vagrant/project/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#13 /vagrant/project/vendor/voryx/event-loop/src/EventLoop.php(43): React\EventLoop\StreamSelectLoop->run()
#14 [internal function]: EventLoop\EventLoop::EventLoop\{closure}()
#15 {main}
```

**Comment by mbonneau** [comment]
@ledazinha - Thank you for tracking this issue down and providing such great information. I have just pushed an update that fixes this.

**Comment by ledazinha** [comment]
@mbonneau Thank you very much
