### ISSUE TITLE
Fatal error: Uncaught Exception: Observer not set on command.

### ISSUE THREAD

**Issue by WyriHaximus** [voryx/PgAsync#44]
Getting the following error in certain situations:

Not sure what is going on, but I suspect it's due to a row lock

```
Fatal error: Uncaught Exception: Observer not set on command. in /opt/app/vendor/voryx/pgasync/src/PgAsync/Command/CommandTrait.php:27
Stack trace:
#0 /opt/app/vendor/voryx/pgasync/src/PgAsync/Connection.php(493): PgAsync\Command\Close->error(Object(Exception))
#1 /opt/app/vendor/voryx/pgasync/src/PgAsync/Connection.php(514): PgAsync\Connection->failAllCommandsWith(Object(Exception))
#2 /opt/app/vendor/voryx/pgasync/src/PgAsync/Connection.php(435): PgAsync\Connection->processQueue()
#3 /opt/app/vendor/voryx/pgasync/src/PgAsync/Connection.php(314): PgAsync\Connection->handleErrorResponse(Object(PgAsync\Message\ErrorResponse))
#4 /opt/app/vendor/voryx/pgasync/src/PgAsync/Connection.php(258): PgAsync\Connection->handleMessage(Object(PgAsync\Message\ErrorResponse))
#5 /opt/app/vendor/voryx/pgasync/src/PgAsync/Connection.php(236): PgAsync\Connection->processData('E\x00\x00\x00USFATAL\x00VFA...')
#6 /opt/app/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): PgAsync\Connection->onData('E\x00\x00\x00USFATAL\x00 in /opt/app/vendor/voryx/pgasync/src/PgAsync/Command/CommandTrait.php on line 27
```

**Comment by mbonneau** [comment]
I'll take a look at this and see if I can reproduce.

**Comment by mbonneau** [comment]
@WyriHaximus Do you know how to reproduce this?

**Comment by WyriHaximus** [comment]
@mbonneau No clue after a year. Should be added more context for you, sorry :(.

**Comment by mbonneau** [comment]
Closing issue - have not encountered in a while - can open a new one if we see it again.

**Comment by WyriHaximus** [comment]
Agreed, I might get back to this when I can reproduce it. Maybe the `'E\x00\x00\x00USFATAL\x00VFA...'` in the backtrace grants a useful hint, but I don't know the inner workings of this package enough for that.
