### ISSUE TITLE
UnderflowException

### ISSUE THREAD

**Issue by leda-ferreira** [voryx/PgAsync#9]
I've got the following error when trying to query the dabase:

```
PHP Fatal error:  Uncaught exception 'UnderflowException' in /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Message/DataRow.php:35
Stack trace:
#0 /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Message/ParserTrait.php(20): PgAsync\Message\DataRow->parseMessage('D\x00\x00\x00k\x00\x0E\x00\x00\x00\x0261\x00\x00...')
#1 /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Connection.php(202): PgAsync\Message\DataRow->parseData('D\x00\x00\x00k\x00\x0E\x00\x00\x00\x0261\x00\x00...')
#2 /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Connection.php(231): PgAsync\Connection->onData('D\x00\x00\x00k\x00\x0E\x00\x00\x00\x0261\x00\x00...')
#3 /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Connection.php(216): PgAsync\Connection->onData('D\x00\x00\x00k\x00\x0E\x00\x00\x00\x0261\x00\x00...')
#4 /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Connection.php(231): PgAsync\Connection->onData('T\x00\x00\x01\x93\x00\x0Enumero_i...')
#5 [internal function]: PgAsync\Connection->onData('T\x in /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Message/DataRow.php on line 35

Fatal error: Uncaught exception 'UnderflowException' in /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Message/DataRow.php:35
Stack trace:
#0 /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Message/ParserTrait.php(20): PgAsync\Message\DataRow->parseMessage('D\x00\x00\x00k\x00\x0E\x00\x00\x00\x0261\x00\x00...')
#1 /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Connection.php(202): PgAsync\Message\DataRow->parseData('D\x00\x00\x00k\x00\x0E\x00\x00\x00\x0261\x00\x00...')
#2 /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Connection.php(231): PgAsync\Connection->onData('D\x00\x00\x00k\x00\x0E\x00\x00\x00\x0261\x00\x00...')
#3 /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Connection.php(216): PgAsync\Connection->onData('D\x00\x00\x00k\x00\x0E\x00\x00\x00\x0261\x00\x00...')
#4 /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Connection.php(231): PgAsync\Connection->onData('T\x00\x00\x01\x93\x00\x0Enumero_i...')
#5 [internal function]: PgAsync\Connection->onData('T\x in /vagrant/www/contactgram/vendor/voryx/pgasync/src/PgAsync/Message/DataRow.php on line 35
```

Code:

``` php
require 'vendor/autoload.php';

$client = new \PgAsync\Client([
    'host' => '127.0.0.1',
    'port' => 5432,
    'user' => 'username',
    'password' => 'password',
    'database' => 'database',
], \EventLoop\getLoop());

$client->query('SELECT * FROM numbers LIMIT 1')->subscribe(
    new \Rx\Observer\CallbackObserver(
        function ($row) {
            var_dump($row);
        },
        function ($e) {
            var_dump($e);
            echo "Failed.\n";
        },
        function () {
            echo "Complete.\n";
        }
    )
);
```

Is this a configuration thing? Do I have to use some specific version of Postgres or turn on/off some setting?

**Comment by mbonneau** [comment]
What version of Postgres are you using? If you can post the table create statement, I will try to reproduce.

**Comment by ledazinha** [comment]
I forgot to add some details: I'm using PostgreSQL 9.3.11 on Ubuntu 14.04.4 LTS, vagrant box ubuntu/trusty32.

**Comment by ledazinha** [comment]
```sql
CREATE TABLE numero
(
  numero_id bigint NOT NULL DEFAULT nextval('numeros_id_numero_seq'::regclass),
  empresa_id bigint NOT NULL,
  tg_username character varying(255),
  tg_phone character varying(255) NOT NULL,
  tg_photo character varying(255),
  tg_lastseen character varying(255),
  tg_printname character varying(255),
  tg_firstname character varying(64),
  tg_lastname character varying(64),
  tg_peer character varying(64),
  tg_id character varying(64),
  profile character varying(255) NOT NULL,
  st_ativo boolean NOT NULL DEFAULT true,
  st_instalado boolean NOT NULL DEFAULT false,
  CONSTRAINT numeros_pkey PRIMARY KEY (numero_id),
  CONSTRAINT numero_empresa_id_fkey FOREIGN KEY (empresa_id)
      REFERENCES empresas (id_empresa) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE CASCADE
)
```

some real data:

```sql
INSERT INTO numero (numero_id, empresa_id, tg_username, tg_phone, tg_photo, tg_lastseen, tg_printname, tg_firstname, tg_lastname, tg_peer, tg_id, profile, st_ativo, st_instalado) VALUES (61, 5, NULL, '5584992227303', NULL, NULL, NULL, 'Contauditoria', NULL, NULL, NULL, 'contaauditoria', true, true);
INSERT INTO numero (numero_id, empresa_id, tg_username, tg_phone, tg_photo, tg_lastseen, tg_printname, tg_firstname, tg_lastname, tg_peer, tg_id, profile, st_ativo, st_instalado) VALUES (63, 12, NULL, '5511940417680', NULL, NULL, NULL, 'Bya Eventos', NULL, NULL, NULL, 'byaeventos', true, true);
INSERT INTO numero (numero_id, empresa_id, tg_username, tg_phone, tg_photo, tg_lastseen, tg_printname, tg_firstname, tg_lastname, tg_peer, tg_id, profile, st_ativo, st_instalado) VALUES (64, 16, '', '556292815499', '', '', '', '', '', '', '', 'autoeste', true, true);
```

**Comment by ledazinha** [comment]
I'm making some tests and I actually can make some queries. Tables with VARCHARs will fail on `SELECT *`, but it works if I specify only non-text columns. Sometimes I can specify one or two text columns among the others, it may or may not work depending on the order of the columns. The following snippet works. If I uncomment "profile", it works; if I uncomment "tg_peer" and "profile", it fails; if I comment out "profile" again, it fails; if I place "tg_peer" after "st_ativo" or "st_instalado", the query works but the column will contain bogus data.

```php
$client = new \PgAsync\Client([
    'host' => '127.0.0.1',
    'port' => 5432,
    'user' => 'username',
    'password' => 'password',
    'database' => 'database',
], \EventLoop\getLoop());

$cols = [
    'numero_id',
    'empresa_id',
    //'tg_username',
    //'tg_phone',
    //'tg_photo',
    //'tg_lastseen',
    //'tg_printname',
    //'tg_firstname',
    //'tg_lastname',
    //'tg_peer',
    //'tg_id',
    //'profile',
    'st_ativo',
    'st_instalado'
];

$cols = implode(', ', $cols);

$client->query("SELECT {$cols} FROM numero LIMIT 3")->subscribe(
    new \Rx\Observer\CallbackObserver(
        function ($row) {
            var_dump($row);
        },
        function ($e) {
            var_dump($e);
            echo "Failed.\n";
        },
        function () {
            echo "Complete.\n";
            \EventLoop\getLoop()->stop();
        }
    )
);
```

**Comment by mbonneau** [comment]
This is some good info - I will see what results I get.

**Comment by davidwdan** [comment]
@ledazinha do you know what encoding you're using?

**Comment by ledazinha** [comment]
@davidwdan Encoding: UTF8, Collation: en_US.UTF-8, Character type: en_US.UTF-8

**Comment by mbonneau** [comment]
@ledazinha - I am unable to reproduce this issue. I have created a unit test here: https://github.com/mbonneau/PgAsync/commit/f2848866e5ac1919bea1df1ebec172928a166dc9

Can you see anything that I might be doing differently?

I am running this on Mac OS 10.11.5 with Postgres 9.5.3 with UTF8 encoding.

(Please note that if you run the tests on your system, it creates a test database and tables)

**Comment by ledazinha** [comment]
You should be able to reproduce with this exact schema:

```sql
CREATE TABLE meh2 (
    id serial NOT NULL,
    txt1 character varying(10),
    n1 integer,
    n2 integer NOT NULL,
    txt2 character varying(10) NOT NULL,
    PRIMARY KEY (id)
)

INSERT INTO meh2 (id, txt1, n1, n2, txt2) VALUES (1, NULL, NULL, 1, 'A');
INSERT INTO meh2 (id, txt1, n1, n2, txt2) VALUES (2, 'B', 2, 2, 'B');
INSERT INTO meh2 (id, txt1, n1, n2, txt2) VALUES (3, 'C', NULL, 3, 'C');
INSERT INTO meh2 (id, txt1, n1, n2, txt2) VALUES (4, NULL, 4, 4, 'D');

SELECT pg_catalog.setval('meh2_id_seq', 4, true);
```

Bellow is the test script. This exact code will throw the exception. Commenting out ids 1 and 3 and column txt1, it works. You can get different results by messing arround with the ids, columns and the order. When it works, NULLs are evaluated as boolean false values.

```php
$client = new \PgAsync\Client([
    'host' => '127.0.0.1',
    'port' => 5432,
    'user' => 'username',
    'password' => 'password',
    'database' => 'database',
], \EventLoop\getLoop());

$order = 'ASC';

$ids = [
    1,
    2,
    3,
    4
];

$cols = [
    'id',
    'txt1',
    'n1',
    'n2',
    'txt2'
];

$ids = implode(', ', $ids);
$cols = implode(', ', $cols);

$client->query("SELECT {$cols} FROM meh2 WHERE id IN ({$ids}) ORDER BY id {$order}")->subscribe(
    new \Rx\Observer\CallbackObserver(
        function ($row) {
            var_dump($row);
        },
        function ($e) {
            echo "Failed.\n";
            \EventLoop\getLoop()->stop();
        },
        function () {
            echo "Complete.\n";
            \EventLoop\getLoop()->stop();
        }
    )
);
```

**Comment by ledazinha** [comment]
@mbonneau Thank you, I'll give it a look. I'm thinking it might be a problem with my PostgreSQL installation, I'll try with different boxes.

**Comment by davidwdan** [comment]
@ledazinha I just tested your latest example and it works with v9.4.5 on OSX

**Comment by ledazinha** [comment]
phpUnit output is bellow. I don't know if I'm running it the right way, though. I did `export USER=postgres` and then `phpunit`. Is this the way to do it? Anyway, I'm setting up a different box now.

```
Password: 
Password for user postgres: 
Password for user postgres: 
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

EFFF.F....                                                        10 / 10 (100%)

Time: 9.65 seconds, Memory: 8.25MB

There was 1 error:

1) PgAsync\Tests\Integration\BoolTest::testBools
Exception: Server asked for password, but none was configured.

/vagrant/other/PgAsync/src/PgAsync/Connection.php:331
/vagrant/other/PgAsync/src/PgAsync/Connection.php:248
/vagrant/other/PgAsync/src/PgAsync/Connection.php:211
/vagrant/other/PgAsync/src/PgAsync/Connection.php:231
/vagrant/other/PgAsync/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
/vagrant/other/PgAsync/vendor/react/stream/src/Stream.php:133
/vagrant/other/PgAsync/vendor/react/event-loop/src/LibEventLoop.php:335
/vagrant/other/PgAsync/vendor/react/event-loop/src/LibEventLoop.php:211
/vagrant/other/PgAsync/tests/TestCase.php:58
/vagrant/other/PgAsync/tests/Integration/BoolTest.php:45

--

There were 4 failures:

1) PgAsync\Tests\Integration\NullPasswordTest::testNullPassword
onError

/vagrant/other/PgAsync/tests/Integration/NullPasswordTest.php:30
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/CallbackObserver.php:40
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/AbstractObserver.php:29
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/AutoDetachObserver.php:42
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/AbstractObserver.php:29
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Subject/Subject.php:88
/vagrant/other/PgAsync/src/PgAsync/Connection.php:422
/vagrant/other/PgAsync/src/PgAsync/Connection.php:331
/vagrant/other/PgAsync/src/PgAsync/Connection.php:248
/vagrant/other/PgAsync/src/PgAsync/Connection.php:211
/vagrant/other/PgAsync/src/PgAsync/Connection.php:231
/vagrant/other/PgAsync/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
/vagrant/other/PgAsync/vendor/react/stream/src/Stream.php:133
/vagrant/other/PgAsync/vendor/react/event-loop/src/LibEventLoop.php:335
/vagrant/other/PgAsync/vendor/react/event-loop/src/LibEventLoop.php:211
/vagrant/other/PgAsync/tests/TestCase.php:58
/vagrant/other/PgAsync/tests/Integration/NullPasswordTest.php:38

2) PgAsync\Tests\Integration\SimpleQueryTest::testSimpleQuery
onError

/vagrant/other/PgAsync/tests/Integration/SimpleQueryTest.php:26
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/CallbackObserver.php:40
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/AbstractObserver.php:29
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/AutoDetachObserver.php:42
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/AbstractObserver.php:29
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Subject/Subject.php:88
/vagrant/other/PgAsync/src/PgAsync/Connection.php:422
/vagrant/other/PgAsync/src/PgAsync/Connection.php:331
/vagrant/other/PgAsync/src/PgAsync/Connection.php:248
/vagrant/other/PgAsync/src/PgAsync/Connection.php:211
/vagrant/other/PgAsync/src/PgAsync/Connection.php:231
/vagrant/other/PgAsync/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
/vagrant/other/PgAsync/vendor/react/stream/src/Stream.php:133
/vagrant/other/PgAsync/vendor/react/event-loop/src/LibEventLoop.php:335
/vagrant/other/PgAsync/vendor/react/event-loop/src/LibEventLoop.php:211
/vagrant/other/PgAsync/tests/TestCase.php:58
/vagrant/other/PgAsync/tests/Integration/SimpleQueryTest.php:34

3) PgAsync\Tests\Integration\SimpleQueryTest::testSimpleQueryNoResult
onError

/vagrant/other/PgAsync/tests/Integration/SimpleQueryTest.php:55
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/CallbackObserver.php:40
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/AbstractObserver.php:29
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/AutoDetachObserver.php:42
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/AbstractObserver.php:29
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Subject/Subject.php:88
/vagrant/other/PgAsync/src/PgAsync/Connection.php:422
/vagrant/other/PgAsync/src/PgAsync/Connection.php:331
/vagrant/other/PgAsync/src/PgAsync/Connection.php:248
/vagrant/other/PgAsync/src/PgAsync/Connection.php:211
/vagrant/other/PgAsync/src/PgAsync/Connection.php:231
/vagrant/other/PgAsync/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
/vagrant/other/PgAsync/vendor/react/stream/src/Stream.php:133
/vagrant/other/PgAsync/vendor/react/event-loop/src/LibEventLoop.php:335
/vagrant/other/PgAsync/vendor/react/event-loop/src/LibEventLoop.php:211
/vagrant/other/PgAsync/tests/TestCase.php:58
/vagrant/other/PgAsync/tests/Integration/SimpleQueryTest.php:63

4) PgAsync\Tests\Integration\SimpleQueryTest::testIssue9

/vagrant/other/PgAsync/tests/Integration/SimpleQueryTest.php:128
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/CallbackObserver.php:40
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/AbstractObserver.php:29
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/AutoDetachObserver.php:42
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Observer/AbstractObserver.php:29
/vagrant/other/PgAsync/vendor/reactivex/rxphp/lib/Rx/Subject/Subject.php:88
/vagrant/other/PgAsync/src/PgAsync/Connection.php:422
/vagrant/other/PgAsync/src/PgAsync/Connection.php:331
/vagrant/other/PgAsync/src/PgAsync/Connection.php:248
/vagrant/other/PgAsync/src/PgAsync/Connection.php:211
/vagrant/other/PgAsync/src/PgAsync/Connection.php:231
/vagrant/other/PgAsync/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
/vagrant/other/PgAsync/vendor/react/stream/src/Stream.php:133
/vagrant/other/PgAsync/vendor/react/event-loop/src/LibEventLoop.php:335
/vagrant/other/PgAsync/vendor/react/event-loop/src/LibEventLoop.php:211
/vagrant/other/PgAsync/tests/TestCase.php:58
/vagrant/other/PgAsync/tests/Integration/SimpleQueryTest.php:140

ERRORS!
Tests: 10, Assertions: 6, Errors: 1, Failures: 4.
```

**Comment by davidwdan** [comment]
@ledazinha instead of setting the `USER` environmental variable, try switching to the user `postgres` and then running the tests

**Comment by ledazinha** [comment]
I just tested in a fresh new box (ubuntu/trusty64), and it worked. I got the same error on both trusty32 (original box) and 2 versions of wily32 (one use an alternative version of php from a third-party ppa) and got the same error on both. Maybe it is an x86/x64 architecture issue?
